const BODIES = [
  // === 8 MAJOR PLANETS ===
  {
    id: "jupiter",
    name: "Jupiter",
    classification: "Planet",
    parent: "Sun",
    massEarth: 317.8,
    diameterEarth: 11.21,
    gravityG: 2.53,
    distanceAU: 5.20,
    atmosphereBar: 1.0, // 1-bar level reference
    color: "#c88b3a",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg/600px-Jupiter_and_its_shrunken_Great_Red_Spot.jpg",
    standingThere: "You cannot stand on Jupiter — there is no surface. At the 1-bar pressure level, winds exceed 600 km/h and the sky is a roiling chaos of ammonia ice and hydrogen sulfide. The sun is a brilliant but distant point, five times fainter than on Earth.",
  },
  {
    id: "saturn",
    name: "Saturn",
    classification: "Planet",
    parent: "Sun",
    massEarth: 95.16,
    diameterEarth: 9.45,
    gravityG: 1.07,
    distanceAU: 9.58,
    atmosphereBar: 1.0,
    color: "#e8d5a3",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Saturn_during_Equinox.jpg/600px-Saturn_during_Equinox.jpg",
    standingThere: "Like Jupiter, Saturn has no solid surface. At the 1-bar level, the rings arc overhead as a vast, razor-thin plane bisecting the sky. The sun is a tenth of Earth's apparent size, casting long amber shadows across cloud bands wider than continents.",
  },
  {
    id: "uranus",
    name: "Uranus",
    classification: "Planet",
    parent: "Sun",
    massEarth: 14.54,
    diameterEarth: 4.01,
    gravityG: 0.89,
    distanceAU: 19.22,
    atmosphereBar: 1.0,
    color: "#7de8e8",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Uranus2.jpg/600px-Uranus2.jpg",
    standingThere: "Uranus rolls on its side — the sun traces a slow spiral rather than rising and setting. At 1 bar, the methane-laced atmosphere is a featureless cyan haze. You weigh slightly less than on Earth, but the cold is unimaginable: −224°C at the cloud tops.",
  },
  {
    id: "neptune",
    name: "Neptune",
    classification: "Planet",
    parent: "Sun",
    massEarth: 17.15,
    diameterEarth: 3.88,
    gravityG: 1.14,
    distanceAU: 30.05,
    atmosphereBar: 1.0,
    color: "#4b70dd",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Neptune_-_Voyager_2_%2829347980845%29_flatten_crop.jpg/600px-Neptune_-_Voyager_2_%2829347980845%29_flatten_crop.jpg",
    standingThere: "The solar wind here carries barely a whisper of warmth. Neptune's supersonic winds — the fastest in the Solar System at 2,100 km/h — tear across a deep cobalt sky. At 1 bar, you weigh 14% more than on Earth, standing in an endless hurricane.",
  },
  {
    id: "earth",
    name: "Earth",
    classification: "Planet",
    parent: "Sun",
    massEarth: 1.0,
    diameterEarth: 1.0,
    gravityG: 1.0,
    distanceAU: 1.0,
    atmosphereBar: 1.013,
    color: "#4fa3e0",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/600px-The_Earth_seen_from_Apollo_17.jpg",
    standingThere: "The reference point for all comparisons. A warm, 1g world with liquid water oceans and a breathable nitrogen-oxygen atmosphere at 1 bar. The sun is a comfortable yellow-white disk, and the horizon sits about 5 km away at sea level.",
  },
  {
    id: "venus",
    name: "Venus",
    classification: "Planet",
    parent: "Sun",
    massEarth: 0.815,
    diameterEarth: 0.949,
    gravityG: 0.904,
    distanceAU: 0.72,
    atmosphereBar: 92.0,
    color: "#e8c97d",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Venus-real_color.jpg/600px-Venus-real_color.jpg",
    standingThere: "At 92 bars, the atmosphere is a supercritical fluid. Moving through it feels like walking through water, and the sun is a vague, dim glow through perpetual sulfuric acid clouds. The surface temperature — 465°C — is hotter than Mercury despite being farther from the Sun.",
  },
  {
    id: "mars",
    name: "Mars",
    classification: "Planet",
    parent: "Sun",
    massEarth: 0.107,
    diameterEarth: 0.532,
    gravityG: 0.379,
    distanceAU: 1.52,
    atmosphereBar: 0.006,
    color: "#c1440e",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/OSIRIS_Mars_true_color.jpg/600px-OSIRIS_Mars_true_color.jpg",
    standingThere: "The sky is a butterscotch pink-brown, tinted by fine iron oxide dust suspended in the thin CO₂ atmosphere. At 38% Earth gravity, each step is an easy bound. Olympus Mons dominates the horizon for hundreds of kilometers — a shield volcano so large the curvature of Mars hides its base.",
  },
  {
    id: "mercury",
    name: "Mercury",
    classification: "Planet",
    parent: "Sun",
    massEarth: 0.0553,
    diameterEarth: 0.383,
    gravityG: 0.38,
    distanceAU: 0.39,
    atmosphereBar: 0.0,
    color: "#9c9c9c",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mercury_in_true_color.jpg/600px-Mercury_in_true_color.jpg",
    standingThere: "The sun looms three times larger than on Earth, blazing at 430°C on the sunlit side. Mercury barely rotates — a solar day lasts two Mercurian years, baking one hemisphere in extreme heat while the other plunges to −180°C. The sky is always black; there is no atmosphere to scatter light.",
  },

  // === 19 ROUNDED MOONS ===
  {
    id: "ganymede",
    name: "Ganymede",
    classification: "Moon",
    parent: "Jupiter",
    massEarth: 0.0248,
    diameterEarth: 0.413,
    gravityG: 0.146,
    distanceAU: 5.20,
    atmosphereBar: 0.0,
    color: "#8a7a6a",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Ganymede_-_Perijove_34_Composite.png/600px-Ganymede_-_Perijove_34_Composite.png",
    standingThere: "The largest moon in the Solar System is bigger than Mercury, yet its gravity is only 15% of Earth's. Jupiter fills nearly a quarter of the sky — an overwhelming banded giant. Beneath the icy crust lies a saltwater ocean larger than all of Earth's oceans combined.",
  },
  {
    id: "titan",
    name: "Titan",
    classification: "Moon",
    parent: "Saturn",
    massEarth: 0.0225,
    diameterEarth: 0.404,
    gravityG: 0.138,
    distanceAU: 9.58,
    atmosphereBar: 1.45,
    color: "#e8a83a",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Titan_in_true_color.jpg/600px-Titan_in_true_color.jpg",
    standingThere: "The air is thick enough and the gravity low enough that if you attached wings to your arms, you could fly. Titan is the only place in the Solar System where you don't need a pressure suit — just a very warm coat and an oxygen mask. Methane rain falls into hydrocarbon lakes on an orange, alien shore.",
  },
  {
    id: "callisto",
    name: "Callisto",
    classification: "Moon",
    parent: "Jupiter",
    massEarth: 0.0180,
    diameterEarth: 0.378,
    gravityG: 0.126,
    distanceAU: 5.20,
    atmosphereBar: 0.0,
    color: "#6b6055",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Callisto.jpg/600px-Callisto.jpg",
    standingThere: "Callisto is the most heavily cratered object in the Solar System, a frozen record of four billion years of bombardment. Its surface is ancient beyond reckoning. Jupiter hangs enormous and still in a black sky, and with gravity at 13% of Earth's, even a gentle walk sends dust floating in slow arcs.",
  },
  {
    id: "io",
    name: "Io",
    classification: "Moon",
    parent: "Jupiter",
    massEarth: 0.0150,
    diameterEarth: 0.286,
    gravityG: 0.183,
    distanceAU: 5.20,
    atmosphereBar: 0.0,
    color: "#e8d44d",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Io_highest_resolution_true_color.jpg/600px-Io_highest_resolution_true_color.jpg",
    standingThere: "Io is the most volcanically active body in the Solar System, its surface repaved by sulfur and silicate lava on a timescale of years. The sky glows faintly yellow from sulfur dioxide frost. Jupiter's tidal forces heat Io's interior relentlessly — standing here, you feel the ground itself is alive.",
  },
  {
    id: "moon",
    name: "The Moon",
    classification: "Moon",
    parent: "Earth",
    massEarth: 0.0123,
    diameterEarth: 0.272,
    gravityG: 0.166,
    distanceAU: 1.0,
    atmosphereBar: 0.0,
    color: "#c8c0b0",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FullMoon2010.jpg/600px-FullMoon2010.jpg",
    standingThere: "The only world beyond Earth that humans have walked. At 17% gravity, dust kicked up by boots falls in perfect parabolas and the footprints last millions of years in the vacuum. Earth hangs overhead — never rising, never setting — its blue face a startling contrast to the grey regolith.",
  },
  {
    id: "europa",
    name: "Europa",
    classification: "Moon",
    parent: "Jupiter",
    massEarth: 0.00804,
    diameterEarth: 0.245,
    gravityG: 0.134,
    distanceAU: 5.20,
    atmosphereBar: 0.0,
    color: "#c8b090",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Europa-moon-with-margins.jpg/600px-Europa-moon-with-margins.jpg",
    standingThere: "Europa's surface is a cracked eggshell of water ice, the youngest terrain in the outer Solar System. Tidal flexing from Jupiter's gravity heats a global ocean beneath, and plumes of water vapor may vent into space. The surface is dangerously irradiated, but below the ice, conditions may support life.",
  },
  {
    id: "triton",
    name: "Triton",
    classification: "Moon",
    parent: "Neptune",
    massEarth: 0.00359,
    diameterEarth: 0.212,
    gravityG: 0.079,
    distanceAU: 30.05,
    atmosphereBar: 0.00001,
    color: "#c8d8e8",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Triton_moon_mosaic_Voyager_2_%28large%29.jpg/600px-Triton_moon_mosaic_Voyager_2_%28large%29.jpg",
    standingThere: "Triton is the coldest measured surface in the Solar System at −235°C — just 38 degrees above absolute zero. It orbits Neptune backwards, a captured Kuiper Belt Object. Nitrogen geysers shoot dark plumes 8 km into its whisper-thin atmosphere. The sun is a distant star, too faint to cast shadows.",
  },
  {
    id: "titania",
    name: "Titania",
    classification: "Moon",
    parent: "Uranus",
    massEarth: 0.000590,
    diameterEarth: 0.124,
    gravityG: 0.038,
    distanceAU: 19.22,
    atmosphereBar: 0.0,
    color: "#a89888",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Titania_%28moon%29_color_cropped.jpg/600px-Titania_%28moon%29_color_cropped.jpg",
    standingThere: "Uranus's largest moon has 4% of Earth's gravity — a careful hop could send you into a slow, weightless arc lasting minutes. Deep canyons slice across the surface, formed as the moon froze and expanded. Uranus appears as a featureless cyan sphere, its rings barely visible as a thin line.",
  },
  {
    id: "rhea",
    name: "Rhea",
    classification: "Moon",
    parent: "Saturn",
    massEarth: 0.000339,
    diameterEarth: 0.120,
    gravityG: 0.026,
    distanceAU: 9.58,
    atmosphereBar: 0.0,
    color: "#d0c8c0",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Rhea_in_natural_color.jpg/600px-Rhea_in_natural_color.jpg",
    standingThere: "Saturn's second-largest moon is an icy world at 2.7% Earth gravity. Saturn's rings cut a perfect, razor-thin arc across the sky. The surface is peppered with ancient craters and bright wispy streaks, possibly water ice exposed by geological activity billions of years ago.",
  },
  {
    id: "oberon",
    name: "Oberon",
    classification: "Moon",
    parent: "Uranus",
    massEarth: 0.000282,
    diameterEarth: 0.119,
    gravityG: 0.035,
    distanceAU: 19.22,
    atmosphereBar: 0.0,
    color: "#988878",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Voyager_2_picture_of_Oberon.jpg/600px-Voyager_2_picture_of_Oberon.jpg",
    standingThere: "Uranus's outermost large moon, Oberon, is a dark, ancient world. At 3.5% Earth gravity, even a light jump becomes a protracted flight. Towering mountains rise from the limb in Voyager images — one, near the terminator, rises 6 km above the surrounding plains.",
  },
  {
    id: "iapetus",
    name: "Iapetus",
    classification: "Moon",
    parent: "Saturn",
    massEarth: 0.000259,
    diameterEarth: 0.115,
    gravityG: 0.022,
    distanceAU: 9.58,
    atmosphereBar: 0.0,
    color: "#888878",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Iapetus_as_seen_by_the_Cassini_probe_-_20071008.jpg/600px-Iapetus_as_seen_by_the_Cassini_probe_-_20071008.jpg",
    standingThere: "Iapetus is a world of two faces — one hemisphere as black as coal, the other gleaming white ice. A colossal equatorial ridge, taller than Mount Everest, encircles the moon like a weld seam. At 2.2% Earth gravity, standing on the ridge crest, you look out over a landscape unlike anything else in the Solar System.",
  },
  {
    id: "charon",
    name: "Charon",
    classification: "Moon",
    parent: "Pluto",
    massEarth: 0.000271,
    diameterEarth: 0.095,
    gravityG: 0.029,
    distanceAU: 39.48,
    atmosphereBar: 0.0,
    color: "#9898a8",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Charon_in_True_Color_-_High-Res.jpg/600px-Charon_in_True_Color_-_High-Res.jpg",
    standingThere: "Charon is so massive relative to Pluto that the two orbit a point in space between them — making it arguably a double-dwarf-planet system. Pluto hangs massive and reddish in Charon's sky, never moving. A deep red polar cap of tholins — complex organic compounds — stains the northern pole.",
  },
  {
    id: "umbriel",
    name: "Umbriel",
    classification: "Moon",
    parent: "Uranus",
    massEarth: 0.000163,
    diameterEarth: 0.092,
    gravityG: 0.023,
    distanceAU: 19.22,
    atmosphereBar: 0.0,
    color: "#606070",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Umbriel_%28moon%29.jpg/600px-Umbriel_%28moon%29.jpg",
    standingThere: "Umbriel is the darkest of Uranus's major moons, its surface ancient and enigmatic. A mysterious bright ring — possibly a fresh impact crater — marks its face in Voyager images. At 2.3% Earth gravity, you could clear a small building in a single leap under its dim, slate-grey skies.",
  },
  {
    id: "ariel",
    name: "Ariel",
    classification: "Moon",
    parent: "Uranus",
    massEarth: 0.000181,
    diameterEarth: 0.092,
    gravityG: 0.025,
    distanceAU: 19.22,
    atmosphereBar: 0.0,
    color: "#b8b0a8",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Ariel_%28moon%29.jpg/600px-Ariel_%28moon%29.jpg",
    standingThere: "Ariel has the youngest, brightest surface of Uranus's moons, crisscrossed by long, deep valleys where the crust was torn apart and resurfaced. At 2.5% gravity, the landscape's extreme topography is accessible with ease — but the temperature holds steady near −213°C.",
  },
  {
    id: "dione",
    name: "Dione",
    classification: "Moon",
    parent: "Saturn",
    massEarth: 0.000184,
    diameterEarth: 0.088,
    gravityG: 0.023,
    distanceAU: 9.58,
    atmosphereBar: 0.0,
    color: "#d8d0c8",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Dione_in_natural_light.jpg/600px-Dione_in_natural_light.jpg",
    standingThere: "Dione is a world of ice and ancient craters, with dramatic cliff faces — 'wispy terrain' — where bright ice walls plunge kilometers into shadowed valleys. Saturn's rings dominate the sky overhead, a shimmering arc stretching horizon to horizon in this 2.3%-g world.",
  },
  {
    id: "tethys",
    name: "Tethys",
    classification: "Moon",
    parent: "Saturn",
    massEarth: 0.000108,
    diameterEarth: 0.083,
    gravityG: 0.015,
    distanceAU: 9.58,
    atmosphereBar: 0.0,
    color: "#e8e8e0",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Tethys_-_March_14_2006_%28PIA08400%29_crop.jpg/600px-Tethys_-_March_14_2006_%28PIA08400%29_crop.jpg",
    standingThere: "Tethys is almost pure water ice. Ithaca Chasma, a grand canyon 2,000 km long and 3–5 km deep, stretches nearly three-quarters around the moon. At 1.5% Earth gravity, descending into it would be a slow, dreamlike fall in the faint glow of distant Saturn.",
  },
  {
    id: "enceladus",
    name: "Enceladus",
    classification: "Moon",
    parent: "Saturn",
    massEarth: 0.0000180,
    diameterEarth: 0.040,
    gravityG: 0.011,
    distanceAU: 9.58,
    atmosphereBar: 0.0,
    color: "#f0f0f8",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Enceladus_from_Voyager.jpg/600px-Enceladus_from_Voyager.jpg",
    standingThere: "Enceladus is the most reflective body in the Solar System, its surface coated in fresh water ice. Near the south pole, massive geysers of liquid water shoot 500 km into space, feeding Saturn's E-ring. At 1.1% gravity, the water plumes around you would look like slow, crystalline fountains ascending to infinity.",
  },
  {
    id: "miranda",
    name: "Miranda",
    classification: "Moon",
    parent: "Uranus",
    massEarth: 0.00000900,
    diameterEarth: 0.037,
    gravityG: 0.008,
    distanceAU: 19.22,
    atmosphereBar: 0.0,
    color: "#a8a098",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Miranda.jpg/600px-Miranda.jpg",
    standingThere: "Miranda is the most geologically chaotic world in the Solar System — a patchwork of ancient terrain, folded ridges, and the 20-km-deep Verona Rupes cliff. At 0.8% Earth gravity, a person falling from that cliff would take 12 minutes to reach the bottom, landing safely at only 60 km/h.",
  },
  {
    id: "mimas",
    name: "Mimas",
    classification: "Moon",
    parent: "Saturn",
    massEarth: 0.00000625,
    diameterEarth: 0.031,
    gravityG: 0.006,
    distanceAU: 9.58,
    atmosphereBar: 0.0,
    color: "#c8c0b8",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Mimas_Cassini.jpg/600px-Mimas_Cassini.jpg",
    standingThere: "With gravity only 1% of Earth's, you could easily jump over a house. The Herschel crater — 130 km wide on a moon only 396 km across — makes Mimas look uncannily like the Death Star. The horizon is strikingly close, dominated by the looming, unblinking presence of Saturn's rings.",
  },

  // === 5 IAU DWARF PLANETS ===
  {
    id: "eris",
    name: "Eris",
    classification: "Dwarf Planet",
    parent: "Sun",
    massEarth: 0.00278,
    diameterEarth: 0.184,
    gravityG: 0.082,
    distanceAU: 67.8,
    atmosphereBar: 0.0,
    color: "#d8d8d8",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Eris_and_dysnomia2.jpg/600px-Eris_and_dysnomia2.jpg",
    standingThere: "Eris is the world that ended Pluto's planetary status. Currently near aphelion, it's three times farther from the sun than Pluto. Its surface is among the most reflective in the Solar System — fresh methane frost covers everything. The sun is a brilliant star, indistinguishable to the naked eye from other bright stars.",
  },
  {
    id: "pluto",
    name: "Pluto",
    classification: "Dwarf Planet",
    parent: "Sun",
    massEarth: 0.00218,
    diameterEarth: 0.186,
    gravityG: 0.063,
    distanceAU: 39.48,
    atmosphereBar: 0.00001,
    color: "#c8956c",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Pluto_in_True_Color_-_High-Res.jpg/600px-Pluto_in_True_Color_-_High-Res.jpg",
    standingThere: "Pluto is a world of nitrogen ice plains, methane snow-capped mountains of water ice, and a vast heart-shaped glacier. New Horizons revealed it as a complex, geologically active world. At 6% Earth gravity, you weigh less than a kilogram. The sky is blue at dusk; the sun casts long, cold shadows over a salmon-colored landscape.",
  },
  {
    id: "haumea",
    name: "Haumea",
    classification: "Dwarf Planet",
    parent: "Sun",
    massEarth: 0.000700,
    diameterEarth: 0.103,
    gravityG: 0.044,
    distanceAU: 43.1,
    atmosphereBar: 0.0,
    color: "#e8e8e8",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Haumea_best_fit_shape_model_overlay.png/600px-Haumea_best_fit_shape_model_overlay.png",
    standingThere: "Haumea spins so fast — one rotation every 3.9 hours — that it has been stretched into the shape of a rugby ball. Standing near the equator, the horizon curves away at a dramatic angle and the sky rotates visibly. A ring system was discovered in 2017, making Haumea the only known TNO with rings.",
  },
  {
    id: "makemake",
    name: "Makemake",
    classification: "Dwarf Planet",
    parent: "Sun",
    massEarth: 0.000500,
    diameterEarth: 0.112,
    gravityG: 0.040,
    distanceAU: 45.8,
    atmosphereBar: 0.0,
    color: "#c8a878",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Makemake_and_its_moon.jpg/600px-Makemake_and_its_moon.jpg",
    standingThere: "Makemake is a reddish world of frozen methane and ethane, tinted by tholins formed when cosmic rays bombard simple organic molecules. Its recently discovered moon orbits in a strangely eccentric path. The sun is a 1,600× fainter than on Earth — you'd need a bright flashlight to read by its light.",
  },
  {
    id: "ceres",
    name: "Ceres",
    classification: "Dwarf Planet",
    parent: "Sun",
    massEarth: 0.000157,
    diameterEarth: 0.074,
    gravityG: 0.029,
    distanceAU: 2.77,
    atmosphereBar: 0.0,
    color: "#888880",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Ceres_-_RC3_-_Haulani_Crater_%2822381131691%29.jpg/600px-Ceres_-_RC3_-_Haulani_Crater_%2822381131691%29.jpg",
    standingThere: "Ceres is the nearest dwarf planet — just 2.77 AU away, in the asteroid belt. Dawn revealed mysterious bright spots in Occator Crater: brine-filled fractures where salty water seeps from a subsurface reservoir. At 2.9% gravity, a strong throw could send a baseball into orbit.",
  },

  // === 5 HIGH-PROBABILITY CANDIDATES ===
  {
    id: "gonggong",
    name: "Gonggong",
    classification: "Candidate",
    parent: "Sun",
    massEarth: 0.000270,
    diameterEarth: 0.098,
    gravityG: 0.028,
    distanceAU: 88.3,
    atmosphereBar: 0.0,
    color: "#c07878",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/225088_Gonggong_with_moon_Xiangliu.jpg/600px-225088_Gonggong_with_moon_Xiangliu.jpg",
    standingThere: "Gonggong is one of the most distant known large objects in the Solar System, near its aphelion at 88 AU. Its red surface is stained with tholins. The sun is a pinpoint star — 88 times fainter than on Earth. It has a small moon, Xiangliu, named after a nine-headed serpent from Chinese mythology.",
  },
  {
    id: "quaoar",
    name: "Quaoar",
    classification: "Candidate",
    parent: "Sun",
    massEarth: 0.000179,
    diameterEarth: 0.087,
    gravityG: 0.028,
    distanceAU: 43.7,
    atmosphereBar: 0.0,
    color: "#a08870",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Quaoar_Weywot.jpg/600px-Quaoar_Weywot.jpg",
    standingThere: "Quaoar surprised astronomers: despite a surface temperature near absolute zero, it has a ring system far beyond the Roche limit — where rings shouldn't exist. Its moon Weywot orbits overhead. The surface is a mix of crystalline water ice and methane frost, slowly reddening under cosmic ray bombardment.",
  },
  {
    id: "sedna",
    name: "Sedna",
    classification: "Candidate",
    parent: "Sun",
    massEarth: 0.000125,
    diameterEarth: 0.082,
    gravityG: 0.021,
    distanceAU: 84.3,
    atmosphereBar: 0.0,
    color: "#c06050",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Sedna_-_orbit_and_comparison_%28crop%29.jpg/600px-Sedna_-_orbit_and_comparison_%28crop%29.jpg",
    standingThere: "Sedna's orbit is one of the most extreme in the Solar System, swinging out to 937 AU at aphelion — nearly 1,000 times Earth's distance from the sun. It is so remote that some astronomers believe it was captured from another star system. At 84 AU now, the sun is a brilliant but heatless point of light.",
  },
  {
    id: "orcus",
    name: "Orcus",
    classification: "Candidate",
    parent: "Sun",
    massEarth: 0.000107,
    diameterEarth: 0.073,
    gravityG: 0.023,
    distanceAU: 39.2,
    atmosphereBar: 0.0,
    color: "#908888",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Orcus-Vanth_system_hst.jpg/600px-Orcus-Vanth_system_hst.jpg",
    standingThere: "Orcus is sometimes called the 'anti-Pluto' — it orbits in resonance with Neptune just as Pluto does, but on the opposite side. Its large moon Vanth orbits closely overhead. The surface is covered in water ice and possibly ammonia hydrates, making it appear distinctly grayish in Hubble images.",
  },
  {
    id: "salacia",
    name: "Salacia",
    classification: "Candidate",
    parent: "Sun",
    massEarth: 0.0000840,
    diameterEarth: 0.068,
    gravityG: 0.021,
    distanceAU: 42.2,
    atmosphereBar: 0.0,
    color: "#909898",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Salacia_with_moon_Actaea.jpg/600px-Salacia_with_moon_Actaea.jpg",
    standingThere: "Salacia is unusually dark for a Kuiper Belt Object, suggesting its surface is covered not in reflective ice but in carbon-rich material. Its moon Actaea is relatively large, hinting at a collisional origin. This world sits in a deep-sky darkness that no human probe has yet visited or photographed up close.",
  },
];

const CLASSIFICATIONS = ["Planet", "Moon", "Dwarf Planet", "Candidate"];
const SORT_OPTIONS = [
  { key: "massEarth", label: "Mass" },
  { key: "gravityG", label: "Gravity" },
  { key: "distanceAU", label: "Distance from Sun" },
  { key: "diameterEarth", label: "Diameter" },
];
